#ifndef PIDCOMMANDS_H
#define PIDCOMMANDS_H

// OBD-II PID Definitions
#define PID_RPM "010C"
#define PID_SPEED "010D"
#define PID_COOLANT_TEMP "0105"
#define PID_INTAKE_TEMP "010F"
#define PID_THROTTLE "0111"
#define PID_ENGINE_LOAD "0104"
#define PID_MANIFOLD_PRESSURE "010B"
#define PID_FUEL_LEVEL "012F"
#define PID_TIMING_ADVANCE "010E"

// ELM327 AT Commands
#define CMD_RESET "ATZ"
#define CMD_ECHO_OFF "ATE0"
#define CMD_LINEFEED_OFF "ATL0"
#define CMD_SPACES_OFF "ATS0"

// Command array for polling (in order)
const char* POLL_COMMANDS[] = {
  PID_RPM,
  PID_SPEED,
  PID_COOLANT_TEMP,
  PID_INTAKE_TEMP,
  PID_THROTTLE,
  PID_ENGINE_LOAD,
  PID_MANIFOLD_PRESSURE,
  PID_FUEL_LEVEL,
  PID_TIMING_ADVANCE
};

const int POLL_COMMANDS_COUNT = 9;

#endif
